// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bcTx.proto

#ifndef PROTOBUF_bcTx_2eproto__INCLUDED
#define PROTOBUF_bcTx_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_bcTx_2eproto();
void protobuf_AssignDesc_bcTx_2eproto();
void protobuf_ShutdownFile_bcTx_2eproto();

class BsTxMsg;
class BsfkMsg;

// ===================================================================

class BsTxMsg : public ::google::protobuf::Message {
 public:
  BsTxMsg();
  virtual ~BsTxMsg();

  BsTxMsg(const BsTxMsg& from);

  inline BsTxMsg& operator=(const BsTxMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BsTxMsg& default_instance();

  void Swap(BsTxMsg* other);

  // implements Message ----------------------------------------------

  BsTxMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BsTxMsg& from);
  void MergeFrom(const BsTxMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 nSerialId = 1;
  inline bool has_nserialid() const;
  inline void clear_nserialid();
  static const int kNSerialIdFieldNumber = 1;
  inline ::google::protobuf::uint32 nserialid() const;
  inline void set_nserialid(::google::protobuf::uint32 value);

  // required uint32 nQtscardnumber = 2;
  inline bool has_nqtscardnumber() const;
  inline void clear_nqtscardnumber();
  static const int kNQtscardnumberFieldNumber = 2;
  inline ::google::protobuf::uint32 nqtscardnumber() const;
  inline void set_nqtscardnumber(::google::protobuf::uint32 value);

  // required uint32 nQtdcategory = 3;
  inline bool has_nqtdcategory() const;
  inline void clear_nqtdcategory();
  static const int kNQtdcategoryFieldNumber = 3;
  inline ::google::protobuf::uint32 nqtdcategory() const;
  inline void set_nqtdcategory(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:BsTxMsg)
 private:
  inline void set_has_nserialid();
  inline void clear_has_nserialid();
  inline void set_has_nqtscardnumber();
  inline void clear_has_nqtscardnumber();
  inline void set_has_nqtdcategory();
  inline void clear_has_nqtdcategory();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 nserialid_;
  ::google::protobuf::uint32 nqtscardnumber_;
  ::google::protobuf::uint32 nqtdcategory_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_bcTx_2eproto();
  friend void protobuf_AssignDesc_bcTx_2eproto();
  friend void protobuf_ShutdownFile_bcTx_2eproto();

  void InitAsDefaultInstance();
  static BsTxMsg* default_instance_;
};
// -------------------------------------------------------------------

class BsfkMsg : public ::google::protobuf::Message {
 public:
  BsfkMsg();
  virtual ~BsfkMsg();

  BsfkMsg(const BsfkMsg& from);

  inline BsfkMsg& operator=(const BsfkMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BsfkMsg& default_instance();

  void Swap(BsfkMsg* other);

  // implements Message ----------------------------------------------

  BsfkMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BsfkMsg& from);
  void MergeFrom(const BsfkMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 nSerialId = 1;
  inline bool has_nserialid() const;
  inline void clear_nserialid();
  static const int kNSerialIdFieldNumber = 1;
  inline ::google::protobuf::uint32 nserialid() const;
  inline void set_nserialid(::google::protobuf::uint32 value);

  // required uint32 nRes = 2;
  inline bool has_nres() const;
  inline void clear_nres();
  static const int kNResFieldNumber = 2;
  inline ::google::protobuf::uint32 nres() const;
  inline void set_nres(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:BsfkMsg)
 private:
  inline void set_has_nserialid();
  inline void clear_has_nserialid();
  inline void set_has_nres();
  inline void clear_has_nres();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 nserialid_;
  ::google::protobuf::uint32 nres_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_bcTx_2eproto();
  friend void protobuf_AssignDesc_bcTx_2eproto();
  friend void protobuf_ShutdownFile_bcTx_2eproto();

  void InitAsDefaultInstance();
  static BsfkMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// BsTxMsg

// required uint32 nSerialId = 1;
inline bool BsTxMsg::has_nserialid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BsTxMsg::set_has_nserialid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BsTxMsg::clear_has_nserialid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BsTxMsg::clear_nserialid() {
  nserialid_ = 0u;
  clear_has_nserialid();
}
inline ::google::protobuf::uint32 BsTxMsg::nserialid() const {
  return nserialid_;
}
inline void BsTxMsg::set_nserialid(::google::protobuf::uint32 value) {
  set_has_nserialid();
  nserialid_ = value;
}

// required uint32 nQtscardnumber = 2;
inline bool BsTxMsg::has_nqtscardnumber() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BsTxMsg::set_has_nqtscardnumber() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BsTxMsg::clear_has_nqtscardnumber() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BsTxMsg::clear_nqtscardnumber() {
  nqtscardnumber_ = 0u;
  clear_has_nqtscardnumber();
}
inline ::google::protobuf::uint32 BsTxMsg::nqtscardnumber() const {
  return nqtscardnumber_;
}
inline void BsTxMsg::set_nqtscardnumber(::google::protobuf::uint32 value) {
  set_has_nqtscardnumber();
  nqtscardnumber_ = value;
}

// required uint32 nQtdcategory = 3;
inline bool BsTxMsg::has_nqtdcategory() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BsTxMsg::set_has_nqtdcategory() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BsTxMsg::clear_has_nqtdcategory() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BsTxMsg::clear_nqtdcategory() {
  nqtdcategory_ = 0u;
  clear_has_nqtdcategory();
}
inline ::google::protobuf::uint32 BsTxMsg::nqtdcategory() const {
  return nqtdcategory_;
}
inline void BsTxMsg::set_nqtdcategory(::google::protobuf::uint32 value) {
  set_has_nqtdcategory();
  nqtdcategory_ = value;
}

// -------------------------------------------------------------------

// BsfkMsg

// required uint32 nSerialId = 1;
inline bool BsfkMsg::has_nserialid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BsfkMsg::set_has_nserialid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BsfkMsg::clear_has_nserialid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BsfkMsg::clear_nserialid() {
  nserialid_ = 0u;
  clear_has_nserialid();
}
inline ::google::protobuf::uint32 BsfkMsg::nserialid() const {
  return nserialid_;
}
inline void BsfkMsg::set_nserialid(::google::protobuf::uint32 value) {
  set_has_nserialid();
  nserialid_ = value;
}

// required uint32 nRes = 2;
inline bool BsfkMsg::has_nres() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BsfkMsg::set_has_nres() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BsfkMsg::clear_has_nres() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BsfkMsg::clear_nres() {
  nres_ = 0u;
  clear_has_nres();
}
inline ::google::protobuf::uint32 BsfkMsg::nres() const {
  return nres_;
}
inline void BsfkMsg::set_nres(::google::protobuf::uint32 value) {
  set_has_nres();
  nres_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_bcTx_2eproto__INCLUDED
